### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [rmmillay/prj-rev-bwfs-dasmoto#4]
There are several properties shared among the 3 `h2` headings:
https://github.com/rmmillay/prj-rev-bwfs-dasmoto/blob/9251c9f67816994169a5a61b3d95f552062c0328/Dasmotos/resources/css/style.css#L10-L32

To avoid repetition in your stylesheet, you could use `h2` as your selector instead for specifying these shared properties:
```css
h2 { 
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
